version: '3.0'

services:
  db:
    image: postgres:12
    container_name: postgres_db_container
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "scheduledb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
  core:
    image: etuteachers:1.0
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db

